spring.application.name=productService


# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://e%2Dshop:e%2Dshop@microservice-freelence.f8tew3n.mongodb.net/product_db?retryWrites=true&w=majority

# Optional (recommended)
spring.data.mongodb.auto-index-creation=true